Css brochure form
joshangeles/c1222-code-solutions pull request #17
Opened 2022-12-07 23:30 UTC by joshangeles

![image](https://user-images.githubusercontent.com/68949703/206319519-6a5d490f-ff17-483c-bd46-d24fe8e2a844.png)

2022-12-09 21:56 UTC, joshangeles commented
![image](https://user-images.githubusercontent.com/68949703/206801961-091fe8e9-c385-473b-8e22-056a6def105b.png)

decreased width

2022-12-12 17:45 UTC, codingcodymiller requested changes

2022-12-12 18:03 UTC, joshangeles commented on css-brochure-form/styles.css
> +  padding: 10 5;
![image](https://user-images.githubusercontent.com/68949703/207120297-c027c4ad-bfce-4bc3-92b3-995e3487e584.png)

Took off padding after realizing it was unneeded, noticed the example picture didn't have bolded text in the button and changed font-weight

2022-12-12 23:39 UTC, codingcodymiller approved these changes

2022-12-12 23:52 UTC, merged