Completed dom-creation exercise. -JA
joshangeles/c1222-code-solutions pull request #50
Opened 2022-12-20 18:53 UTC by joshangeles

![dom-creation](https://user-images.githubusercontent.com/68949703/208744070-058f8173-cdb2-4b00-9292-351f9621f166.gif)

2022-12-21 17:47 UTC, codingcodymiller requested changes

2022-12-21 17:47 UTC, codingcodymiller commented on dom-creation/main.js
> +var columnThird;
This should not be global.

2022-12-21 18:22 UTC, joshangeles commented
![dom-creation-attempt-2](https://user-images.githubusercontent.com/68949703/208976528-1cc95e42-a196-492f-8957-76bf9db69b59.gif)

Changed scope of columnThird variable and page still generates as before.

2022-12-27 17:23 UTC, codingcodymiller approved these changes

2022-12-27 17:24 UTC, merged